name: Run app
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # If you use SQL Server via pyodbc, you need the driver & headers
      - name: Install ODBC driver
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run your script with SQL_PASS injected as an env var
      - name: Run app
        env:
          SQL_PASS: ${{ secrets.SQL_PASS }}   # must exist in Settings > Secrets > Actions
        run: |
          python r2r3-application.py
