name: Run app
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt || true
      - name: Create .env from SQL_PASS secret
        run: |
          printf "SQL_PASS=%s\n" "$SQL_PASS" > .env
        env:
          SQL_PASS: ${{ secrets.SQL_PASS }}
      - run: python app.py
